//! Generator for `docs/language-forms.md` — the machine-checked reference
//! for the S-expression design language. Every section is rendered from a
//! table the implementation itself dispatches on, so the docs cannot
//! drift from the evaluator:
//!
//!   - `src/eval/forms.zig`          special forms, builtin operators,
//!                                   design-scope forms (+ arity schema)
//!   - `src/eval/fmt.zig`            `(fmt …)` directive table
//!   - `src/sexpr/tokenizer.zig`     SI numeric-literal suffix tables
//!   - `src/render_block_types.zig`  section-name classifier keywords
//!   - `src/eval/check_grammar.zig`  requirement-check grammar (`check_docs`,
//!                                   the same table `parseCheck` dispatches on)
//!   - `src/eval/thermal.zig`        the `(thermal …)` / `(power …)` grammar
//!                                   (`thermal_field_docs`, `power_form_doc`)
//!
//! Three enforcement layers keep it honest: `requireAllDocumented` in
//! forms.zig turns an undocumented form into a compile error; per-table
//! sync tests (e.g. fmt's directive-dispatch test) prove each table
//! matches its dispatch; and `zig build test` runs
//! `gen-language-docs --check` plus the drift test below, so a stale
//! committed file fails the build. Regenerate with `zig build docs`.

const std = @import("std");
const infra_fs = @import("infra/fs.zig");
const forms = @import("eval/forms.zig");
const fmt_mod = @import("eval/fmt.zig");
const tokenizer_mod = @import("sexpr/tokenizer.zig");
const attrs_mod = @import("eval/attrs.zig");
const block_types = @import("render_block_types.zig");
const check_grammar = @import("eval/check_grammar.zig");
const authored_rules = @import("eval/authored_rules.zig");
const thermal = @import("eval/thermal.zig");
const numeric = @import("numeric.zig");
const preflight = @import("preflight.zig");
const review_registry = @import("review_registry.zig");

/// Render the full Markdown reference. The output is deterministic — the
/// build's docs-check step and the drift test below compare it to the
/// checked-in `docs/language-forms.md`. Caller owns the returned slice.
pub fn renderLanguageReference(allocator: std.mem.Allocator) std.mem.Allocator.Error![]const u8 {
    var buf: std.Io.Writer.Allocating = .init(allocator);
    defer buf.deinit();
    renderTo(&buf.writer) catch return error.OutOfMemory;
    return buf.toOwnedSlice();
}

fn renderTo(writer: anytype) !void {
    try writer.writeAll(
        \\# S-Expression Language: Form Reference
        \\
        \\<!-- Auto-generated by src/docgen.zig from the evaluator's own
        \\     dispatch tables. Do not edit by hand — run `zig build docs`
        \\     to regenerate; `zig build test` fails when this file is stale. -->
        \\
        \\Every special form, builtin operator, fmt directive, numeric-literal
        \\suffix, and design-scope form the toolchain recognises, with arity
        \\contracts and one-line summaries. The hand-written prose lives in
        \\[`sexp-language.md`](sexp-language.md); this file is the
        \\machine-checked grammar surface.
        \\
        \\## Special forms
        \\
        \\Arguments are passed un-evaluated; each form decides what to evaluate.
        \\
        \\| Form | Arity | Summary |
        \\| --- | --- | --- |
        \\
    );
    for (forms.special_form_docs, 0..) |doc, i| {
        const variant: forms.SpecialForm = @fromBackingInt(@intCast(i));
        try writer.writeAll("| `");
        try writeCell(writer, doc.syntax);
        try writer.writeAll("` | ");
        try writeArity(writer, forms.schemaFor(variant));
        try writer.writeAll(" | ");
        try writeCell(writer, doc.summary);
        try writer.writeAll(" |\n");
    }

    try renderStructuralForms(writer);

    try writer.writeAll(
        \\
        \\## Builtin operators
        \\
        \\Arithmetic, comparison, and logic operators. Arguments are evaluated left-to-right before the operator runs.
        \\
        \\| Form | Summary |
        \\| --- | --- |
        \\
    );
    for (forms.builtin_docs) |doc| {
        try writer.writeAll("| `");
        try writeCell(writer, doc.syntax);
        try writer.writeAll("` | ");
        try writeCell(writer, doc.summary);
        try writer.writeAll(" |\n");
    }

    try writer.writeAll(
        \\
        \\## String formatting directives
        \\
        \\Specifiers accepted in a `(fmt "template" args…)` template. Each
        \\consumes the next argument of the listed type (or none).
        \\
        \\| Directive | Argument | Summary |
        \\| --- | --- | --- |
        \\
    );
    for (fmt_mod.directives) |d| {
        try writer.print("| `~{c}` | {s} | {s} |\n", .{
            d.spec,
            switch (d.arg) {
                .value => "value",
                .number => "number",
                .string => "string",
                .none => "—",
            },
            d.summary,
        });
    }

    try writer.writeAll(
        \\
        \\## Numeric literals
        \\
        \\Bare numbers accept an SI scale suffix, optionally followed by one
        \\unit letter that carries no scale (`100nF` == `100n`); a unit
        \\letter may also stand alone (`3.3V` == `3.3`). The suffix must end
        \\the token — `100kHz` falls through to a plain atom. Dimension
        \\tokens are separate: `mm` keeps the value in millimetres and `mil`
        \\converts to mm (1 mil = 0.0254 mm).
        \\
        \\| Suffix | Scale | Notes |
        \\| --- | --- | --- |
        \\
    );
    for (tokenizer_mod.si_scales) |s| {
        try writer.print("| `{c}` | 10^{d} | {s} |\n", .{
            s.letter,
            multiplierExponent(s.multiplier),
            if (s.bare) "" else "Only with a unit letter (`100mV`) — bare `3m`, `mm`, `mil` keep their dimension meanings.",
        });
    }
    try writer.writeAll("\nUnit letters (scale-free): ");
    for (tokenizer_mod.si_unit_letters, 0..) |u, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("`{c}`", .{u});
    }
    try writer.print(
        ". A trailing `{c}` closes a literal the same way (`10%`, `0.1%`) and " ++
            "likewise carries no scale — `10%` is the number 10 that remembers " ++
            "its spelling, not 0.1.\n",
        .{tokenizer_mod.percent_sign},
    );
    try writer.writeAll(
        \\
        \\A suffixed literal keeps its source text. The value is still a plain
        \\number in arithmetic, but anywhere it is written back out as a part
        \\value it renders by its unit: `(pullup "SDA" 4.7k …)` is a 4.7k
        \\resistor, not a `4700` one, and `(cap-0402 100nF)` is the same as
        \\`(cap-0402 "100nF")` rather than `0.0000001`.
        \\
    );

    try renderTypedAttributes(writer);

    try renderScopeForms(writer);

    try renderSubFormSections(writer);

    try renderClassifierKeywords(writer);

    try renderReferenceAppendices(writer);
}

/// Render the "Structural control flow" section from
/// `forms.structural_form_docs`: the special forms that are ALSO design-scope
/// statements, with the same D/S/s scope column the design-scope table uses.
fn renderStructuralForms(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Structural control flow
        \\
        \\The special forms above that are also design-scope STATEMENTS: their
        \\body holds whatever the enclosing scope accepts, so a whole
        \\sub-circuit can be conditional or repeated. The scope column reads
        \\as it does for design-scope forms: **D** = design-block top level,
        \\**S** = section, **s** = sub-section. A body form illegal in the
        \\enclosing scope is reported at its own source location, exactly as a
        \\hand-written sibling would be.
        \\
        \\Identity: the OUTERMOST structural form owns one source-resident
        \\`(id …)` anchor, minted by the build when missing. Every child it
        \\emits derives its id from that anchor, the child's own stable origin
        \\key, and the accumulated key path of the enclosing branches and
        \\iterations — so nesting composes and a condition flip cannot alias a
        \\then-child with an else-child. An `(ids ("origin@key" hex8)…)`
        \\sidecar on the anchor form pins migrated identities.
        \\
        \\| Form | Scope | Identity |
        \\| --- | --- | --- |
        \\
    );
    for (forms.structural_form_docs) |row| {
        const doc = forms.special_form_docs[@backingInt(row.form)];
        try writer.writeAll("| `");
        try writeCell(writer, doc.syntax);
        try writer.writeAll("` | ");
        if (row.scope.design_block) try writer.writeAll("D") else try writer.writeAll("·");
        if (row.scope.section) try writer.writeAll("S") else try writer.writeAll("·");
        if (row.scope.sub_section) try writer.writeAll("s") else try writer.writeAll("·");
        try writer.writeAll(" | ");
        try writeCell(writer, row.identity);
        try writer.writeAll(" |\n");
    }
}

/// Render the "Typed attributes" section from `eval/attrs.zig`'s slot table —
/// the same table evaluation classifies against, so a new slot cannot reach
/// the language without reaching its reference.
fn renderTypedAttributes(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Typed attributes on a family instantiation
        \\
        \\A component-family call takes a value and then any number of
        \\attributes, written bare or keyed — `(cap-0402 "1uF" x7r "10%" "25V")`
        \\and `(cap-0402 "1uF" (dielectric x7r) (tolerance 10%) (rating 25V))`
        \\mean exactly the same thing. Each attribute that can be placed lands
        \\on the instance as the property below, which is the one source the
        \\BOM, `lib/parts/` row selection, the rating checks, the PDN screen and
        \\the KiCad export read. An unknown keyed attribute is an error with a
        \\did-you-mean; a repeated one is an error. A bare attribute that fits
        \\no slot (`DNP`, `green`, `jumper`, `600R@100MHz`) stays a raw
        \\attribute, untouched.
        \\
        \\| Keys | Property | Selects a parts row |
        \\| --- | --- | --- |
        \\
    );
    inline for (@typeInfo(attrs_mod.Slot).@"enum".field_names, 0..) |_, index| {
        const slot: attrs_mod.Slot = @fromBackingInt(@intCast(index));
        var first = true;
        for (attrs_mod.keyed_spellings) |spelling| {
            if (spelling.slot != slot) continue;
            try writer.print("{s}`{s}`", .{ if (first) "| " else ", ", spelling.key });
            first = false;
        }
        try writer.print(" | `{s}` | {s} |\n", .{
            slot.propertyKey(),
            if (slot.isSelectionColumn()) "yes" else "no — an analysis override",
        });
    }
}

/// Render the "Design-scope forms" section from `forms.scope_form_docs`, the
/// same table the design-block / section dispatch switches on.
fn renderScopeForms(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Design-scope forms
        \\
        \\Forms that may appear directly inside a `(design-block …)`, a
        \\`(section …)`, or a nested sub-section. The scope column lists
        \\where each is accepted: **D** = design-block top level,
        \\**S** = section, **s** = sub-section.
        \\
        \\| Form | Scope | Summary |
        \\| --- | --- | --- |
        \\
    );
    for (forms.scope_form_docs) |row| {
        try writer.writeAll("| `");
        try writeCell(writer, row.doc.syntax);
        try writer.writeAll("` | ");
        if (row.scope.design_block) try writer.writeAll("D") else try writer.writeAll("·");
        if (row.scope.section) try writer.writeAll("S") else try writer.writeAll("·");
        if (row.scope.sub_section) try writer.writeAll("s") else try writer.writeAll("·");
        try writer.writeAll(" | ");
        try writeCell(writer, row.doc.summary);
        try writer.writeAll(" |\n");
    }
}

/// Render one sub-form registry as a `| Form | Summary |` table. A row that
/// nests inside a sibling carries its parent in the syntax template, so the
/// nesting is visible without a second column.
fn renderSubFormTable(writer: anytype, table: []const forms.SubFormDoc) !void {
    try writer.writeAll("\n| Form | Summary |\n| --- | --- |\n");
    for (table) |row| {
        try writer.writeAll("| `");
        try writeCell(writer, row.syntax);
        try writer.writeAll("` | ");
        try writeCell(writer, row.summary);
        try writer.writeAll(" |\n");
    }
}

/// The compound forms whose bodies have their own grammar one level down.
/// Each section is rendered from the registry the evaluator derives its
/// accepted-children list from, so the two cannot drift.
fn renderSubFormSections(writer: anytype) !void {
    try renderInstanceSubForms(writer);
    try renderSubBlockSubForms(writer);
    try renderInterfaceSubForms(writer);
    try renderPortSubForms(writer);
    try renderMarkerForms(writer);
}

fn renderReferenceAppendices(writer: anytype) !void {
    try renderSystemForms(writer);
    try renderComponentFields(writer);
    try renderThermalForms(writer);
    try renderRequirementChecks(writer);
    try renderNetRulePredicates(writer);
    try renderDatasheetReview(writer);
    try renderReviewChecks(writer);
}

/// Render the `(instance …)` and `(pins …)` body grammars — the two ways a
/// placed part's pins reach nets.
fn renderInstanceSubForms(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Instance sub-forms
        \\
        \\The body of an `(instance "REF" component …)`. A bare string child is
        \\positional shorthand for the next physical pad (`(instance "R1"
        \\(res-0402 "10k") "VIN" "TAP")` wires pads 1 and 2), and any
        \\`(key "value")` child whose head is NOT one of the reserved forms
        \\below becomes an inline **property** override on the placed part —
        \\that is how `(mpn "…")`, `(class ldo)` and
        \\`(module-bypass "reason")` are written. A property child whose value
        \\is not a string is dropped with a warning.
        \\
        \\Rows written inside a sibling form show that nesting in their
        \\template.
        \\
    );
    try renderSubFormTable(writer, forms.instance_form_docs);
    try writer.writeAll(
        \\
        \\A `(pins "REF" …)` block wires an already-placed part out of line,
        \\usually one section down from where the instance is declared. Its
        \\children:
        \\
    );
    try renderSubFormTable(writer, forms.pins_form_docs);
}

/// Render the `(sub-block …)` body grammar — above all `(bridge …)`, the
/// form that wires a module's ports to board nets.
fn renderSubBlockSubForms(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Sub-block sub-forms
        \\
        \\Children of a `(sub-block "name" (module-call …) …)`. Anything else
        \\is rejected with a warning rather than going silently dead.
        \\
        \\`(bridge …)` is how hierarchy is wired. Each bridged port `P` emits
        \\one net tie between board net `PREFIX<suffix>` and module net
        \\`<name>/P`, where `<suffix>` is `P` unless `(rename P SUFFIX)`
        \\overrides it. Two idioms are in use: a shared prefix for a peripheral
        \\bus (`(bridge "IMU_" SCK MOSI MISO (rename CS NCS))`), and an empty
        \\prefix with one `(rename PORT NET)` per port, which reads as a
        \\port-to-net map. Power and ground ports are normally left off the
        \\list — they stay wired through the consolidated `(net …)` rail forms.
        \\
    );
    try renderSubFormTable(writer, forms.sub_block_form_docs);
}

/// Render the interface-bundle grammars — the definition, the module-side
/// `(port-group …)` options, and the board-side `(bridge-interface …)`
/// children.
fn renderInterfaceSubForms(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Interface sub-forms
        \\
        \\`bus-port`/`bus-net` write a bus whose lanes are NUMBERED. SPI, I²C,
        \\UART, SWD and JTAG lanes are NAMED, and the names have variants
        \\(`SCK`/`SCLK`, `MOSI`/`SDI`, `CS`/`CSN`/`NCS`/`SS`). An
        \\`(interface …)` definition states one vocabulary once. Its body:
        \\
    );
    try renderSubFormTable(writer, forms.interface_form_docs);
    try writer.writeAll(
        \\
        \\`spi`, `i2c`, `uart`, `swd` and `jtag` ship with the binary under
        \\`stdlib/interfaces/`; a project shadows one by writing its own
        \\`lib/interfaces/<name>.sexp`, and an `(interface …)` at the top level
        \\of a design or module file needs no file at all.
        \\
        \\A module declares its side of the bus with `(port-group …)`, which
        \\expands to one `(port …)` per signal and records the bundle. Its
        \\options:
        \\
    );
    try renderSubFormTable(writer, forms.port_group_form_docs);
    try writer.writeAll(
        \\
        \\A board wires the whole bundle with one `(bridge-interface …)` inside
        \\the `(sub-block …)`, in place of one `(bridge … (rename …))` per
        \\signal. Its children:
        \\
    );
    try renderSubFormTable(writer, forms.bridge_interface_form_docs);
}

/// Render the `(port …)` option grammar.
fn renderPortSubForms(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Port sub-forms
        \\
        \\Parenthesised options of a `(port …)` declaration, in any order after
        \\the direction. Bare-token options sit alongside them: `optional`
        \\marks the port as not required by the module contract, and a
        \\signal-type keyword (`power`, `clock`, `rf`, …) sets the port kind.
        \\Two older bare-token spellings still work and each record a
        \\`deprecated_form` info: `role R` / `protocol P` / `class C` consume
        \\the following token as metadata (write `(role R)` …), and a bare
        \\number is the nominal voltage (write `(nominal V)`). An unrecognised
        \\option warns.
        \\
    );
    try renderSubFormTable(writer, forms.port_form_docs);
}

/// Render the identity/layout markers accepted in design scope.
fn renderMarkerForms(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Identity and layout markers
        \\
        \\Head atoms accepted wherever design-scope forms are, carrying
        \\identity or layout intent rather than circuit content. They are inert
        \\in the scope dispatch — listed here so they never look like a typo
        \\and never draw an unknown-sub-form warning.
        \\
    );
    try renderSubFormTable(writer, forms.marker_form_docs);
}

/// Render the system-contract grammar from the same registry
/// `src/system_sexp.zig` proves its accepted head atoms against. These forms
/// live in their own section because they are not evaluator forms: they belong
/// to `src/systems/<name>/system.sexp`, never to a design.
fn renderSystemForms(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## System contract forms
        \\
        \\The body grammar of `src/systems/<name>/system.sexp` — the contract
        \\`netlisp system-check`, the readiness gate and the `/systems` pages
        \\read. It parses into the same strict `netlisp-system-review-v1` spec
        \\the older hand-maintained `system.json` parses to; where both files
        \\exist the `.sexp` is the contract and readiness reports the JSON as
        \\shadowed. `netlisp tool convert-system-manifest` prints the
        \\equivalent source for an existing JSON manifest.
        \\
        \\These forms are never evaluated, so none of them is valid in a
        \\design source. Rows written inside a sibling form show that nesting
        \\in their template.
        \\
    );
    try renderSubFormTable(writer, forms.system_form_docs);
}

/// Render the `(component …)` / `(component-family …)` library-definition
/// fields from the same registry `eval/modules.zig` skips over.
fn renderComponentFields(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Component library fields
        \\
        \\The body of a `lib/components/<name>.sexp` definition. A
        \\`(component …)` is a fixed part; a `(component-family …)` is
        \\parameterised by one `(parameter …)` the call site supplies, as in
        \\`(cap-0402 "100nF")`. Any other `(key "value")` child is an inline
        \\**property** carried onto every placed instance — `(class ldo)`,
        \\`(mpn "…")` and `(manufacturer "…")` are all properties, not fields.
        \\
    );
    try renderSubFormTable(writer, forms.component_form_docs);
}

/// Render the "Section-name classifier keywords" section from the
/// `render_block_types` name-rule table and the `Category` enum.
fn renderClassifierKeywords(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Section-name classifier keywords
        \\
        \\An explicit `(category <key>)` in the section body is the source of
        \\truth. Only a section without one is classified by these rules:
        \\case-insensitive keyword match on the section **name**, walked in
        \\priority order (first hit wins), falling back to **connector** when
        \\the section contains a J/P-prefixed instance, else **peripheral**.
        \\A section a NAME keyword classified is reported as a
        \\`section_category_inferred` ERC info naming the `(category …)` line
        \\that would pin it.
        \\
        \\| Category | Name keywords |
        \\| --- | --- |
        \\
    );
    for (block_types.name_rules) |rule| {
        try writer.print("| {s} | ", .{@tagName(rule.category)});
        for (rule.keywords, 0..) |kw, i| {
            if (i > 0) try writer.writeAll(", ");
            try writer.print("`{s}`", .{kw});
        }
        try writer.writeAll(" |\n");
    }
    try writer.writeAll("\nValid `(category <key>)` keys: ");
    for (std.enums.values(block_types.Category), 0..) |cat, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("`{s}`", .{@tagName(cat)});
    }
    try writer.writeAll(".\n");
}

/// Render the "Thermal declarations" section from the tables `eval/thermal.zig`
/// parses with: the library `(thermal …)` sub-forms and the instance-scope
/// `(power …)` form.
fn renderThermalForms(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Thermal declarations
        \\
        \\What a part can take, and what it burns — the two inputs to the
        \\screening thermal analysis (`Tj = Ta + P·θJA`, lumped, no layout
        \\coupling). A library part declares its envelope with `(thermal …)`
        \\inside its `(component …)` / `(component-family …)` body; an
        \\instance declares its dissipation with `(power …)` in its own body.
        \\Both are optional: a part with no `(thermal (theta-ja …))` is
        \\screened against a package estimate, and a part with no `(power …)`
        \\has its dissipation derived from annotated pin currents or, for a
        \\regulator module, from its back-computed conversion loss.
        \\
        \\| Form | Summary |
        \\| --- | --- |
        \\
    );
    for (thermal.thermal_field_docs) |doc| {
        try writer.writeAll("| `");
        try writeCell(writer, doc.syntax);
        try writer.writeAll("` | ");
        try writeCell(writer, doc.summary);
        try writer.writeAll(" |\n");
    }
    try writer.writeAll("| `");
    try writeCell(writer, thermal.power_form_doc.syntax);
    try writer.writeAll("` | ");
    try writeCell(writer, thermal.power_form_doc.summary);
    try writer.writeAll(" |\n");
}

/// Render the "Requirement checks" section from `check_grammar.check_docs` —
/// the same table `parseCheck` dispatches on, so the documented grammar can
/// never drift from the checker.
fn renderRequirementChecks(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Requirement checks
        \\
        \\Machine-checkable rules that hang off a library
        \\`(requirement "text" (check …))` form — the executable half of a
        \\datasheet rule. Each is evaluated per placement of the part against
        \\its **containing block** (a sub-block's check sees the sub-block's
        \\nets, not the parent's). Pin references use the pinout **function
        \\name** (`"VDD"`, `"EP"`) or a physical pad id. A rule is inherited by
        \\every design instantiating the part; outcomes surface in `netlisp
        \\check`, the review doc, and the CLI `run_checks` /
        \\`list_component_requirements` tools. Author them with the
        \\`add_component_requirement` CLI tool, whose `check` argument is one
        \\`(check …)` form using one of the primitives below.
        \\
        \\| Check form | Asserts (against the containing block) |
        \\| --- | --- |
        \\
    );
    for (check_grammar.check_docs) |d| {
        try writer.writeAll("| `");
        try writeCell(writer, d.syntax);
        try writer.writeAll("` | ");
        try writeCell(writer, d.summary);
        try writer.writeAll(" |\n");
    }
}

/// Render the "Net-rule predicates" section from
/// `eval/authored_rules.predicate_docs` — the same table `parsePredicate`
/// dispatches on, so a design-owned net rule's vocabulary cannot drift from
/// the reference the way a hand-written list would.
fn renderNetRulePredicates(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Net-rule predicates
        \\
        \\Assertions a design-owned `(net-rule "text" (nets GLOB…) …)` makes
        \\about each net its globs match. Unlike a `(check …)`, which is aimed
        \\at one placement of a part, these are properties of the net itself,
        \\so they need no pinout and no `(on …)` target. A rule may carry
        \\several: the net must satisfy every one of them. See
        \\“Design-owned rules” in the language guide for the
        \\glob syntax, the scopes the form is accepted at, and how the results
        \\reach `netlisp check`.
        \\
        \\| Predicate | Asserts (per matched net) |
        \\| --- | --- |
        \\
    );
    for (authored_rules.predicate_docs) |d| {
        try writer.writeAll("| `");
        try writeCell(writer, d.syntax);
        try writer.writeAll("` | ");
        try writeCell(writer, d.summary);
        try writer.writeAll(" |\n");
    }
}

/// Render the "Review checks" section from `review_registry.rows` — the same
/// static catalogue every review surface cites, grouped by the twelve fixed
/// review categories in category order.
fn renderReviewChecks(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Review checks
        \\
        \\Every check the toolchain can run, with the stable id a finding
        \\cites it by. The engines keep their own vocabularies — electrical-rule
        \\violation kinds, design-rule check kinds, fabrication finding ids,
        \\preflight findings and class-profile item codes, requirement-check and
        \\net-rule keywords, rail, thermal, loop and interface verdicts — and
        \\`src/review_registry.zig` maps each of them onto one row below.
        \\
        \\A row's **scope** is what one finding is about; **closes with** is the
        \\form or action that makes it pass; **policy** is how hard it blocks
        \\(`blocking` stops a release, `waivable` stops one until a waiver record
        \\is linked, `advisory` never does). Results use the seven-word verdict
        \\vocabulary: `pass`, `fail`, `unproven` (the engine ran and names the
        \\missing input), `waived`, `not-applicable`, `not-declared` (the board
        \\never gave the engine an input) and `manual`.
        \\
    );
    for (std.enums.values(review_registry.Category)) |category| {
        try writer.print("\n### {s}\n\n", .{category.title()});
        try writer.writeAll(
            \\| Check | Layer | Scope | Asserts | Closes with | Policy |
            \\| --- | --- | --- | --- | --- | --- |
            \\
        );
        try renderReviewCategoryRows(writer, category);
    }
}

/// Render one category's rows of the "Review checks" table, in registry order.
fn renderReviewCategoryRows(writer: anytype, category: review_registry.Category) !void {
    for (review_registry.rows) |row| {
        if (row.category != category) continue;
        try writer.writeAll("| `");
        try writeCell(writer, row.id);
        try writer.print("` | {s} | {s} | ", .{ @tagName(row.layer), @tagName(row.scope) });
        try writeCell(writer, row.asserts);
        try writer.writeAll(" | ");
        try writeCell(writer, row.closes_with);
        try writer.print(" | {s} |\n", .{@tagName(row.policy)});
    }
}

fn renderDatasheetReview(writer: anytype) !void {
    try writer.writeAll(
        \\
        \\## Datasheet review preflight
        \\
        \\A component declares the datasheets that document it with one
        \\`(datasheet "…")` field per PDF, directly inside its
        \\`lib/components/<name>.sexp` definition:
        \\
        \\```lisp
        \\(component lm66100
        \\  (footprint sc70-6)
        \\  (datasheet "LM66100DCKR.pdf"))
        \\```
        \\
        \\The value is either a filename in `lib/datasheets/` or an absolute
        \\`http(s)` URL (for a PDF that may not be redistributed). This one
        \\field is what fills each placed instance's `docs.datasheets`, what
        \\`describe_component` reports under `datasheets`, what a
        \\`(datasheet-review …)` record must name, and what the datasheet
        \\coverage check requires of every active IC — a PDF sitting in
        \\`lib/datasheets/` that no component declares documents nothing. The
        \\whole chain has CLI tools: `fetch_datasheet` (URL → the PDF on disk),
        \\`attach_datasheet` (PDF → this declaration), `read_datasheet` (text +
        \\the `sha256` to cite below).
        \\
        \\Active-component library records may bind their requirement review
        \\to an exact PDF using `(datasheet-review …)`. `read_datasheet`
        \\returns the current PDF `sha256`; replacing that file automatically
        \\makes the review stale. A complete record has this shape:
        \\
        \\```lisp
        \\(datasheet-review
        \\  (datasheet "part.pdf")
        \\  (sha256 "<64 lowercase hex characters>")
        \\  (status complete)
        \\  (reviewed-by "agent-or-human")
        \\  (date "YYYY-MM-DD")
        \\  (category supply)
        \\  (category-na sequencing "reason this topic is not applicable"))
        \\```
        \\
        \\Every component requirement must cite that PDF with a 1-based page
        \\and a short source quote. `netlisp check --profile preflight` and CLI
        \\`run_checks {profile:"preflight"}` gate incomplete reviews and
        \\unverified manual requirements. Authoring mode reports those legacy
        \\gaps as warnings. `--profile release` is preflight plus the
        \\component-class profile obligations (`profile_incomplete` findings:
        \\supply pins without voltage-range and decoupling checks or current
        \\annotations, control pins without `(electrical …)` thresholds, class
        \\review categories, missing `(thermal …)`, a loop or mixer class with no
        \\gated analysis form), at least one cited requirement on every active
        \\part, and the evaluator's own warnings (an unknown sub-form is an
        \\error). A component binds its class with `(class <key>)` — one of
        \\`ldo`, `switching-regulator`, `protection`, `load-switch`, `mcu`,
        \\`level-shifter`, `pll-loop`, `integrated-synthesizer`,
        \\`clock-jitter-cleaner`, `crystal-oscillator`, `rf-amplifier`, `mixer`,
        \\`rf-attenuator-switch`, `rf-passive`, `rf-detector`, `op-amp`, `sensor`,
        \\`connectors`, `power-path-passives` — else the class is inferred from
        \\its pin function names. Required review categories are:
    );
    try writer.writeAll(" ");
    for (preflight.required_review_categories, 0..) |category, index| {
        if (index > 0) try writer.writeAll(", ");
        try writer.print("`{s}`", .{category});
    }
    try writer.writeAll(". Each must use `(category KEY)` or a `(category-na KEY \"rationale\")`.\n");
}

/// Slice one `## `-headed section out of a rendered reference (heading
/// line through the byte before the next `## ` heading, or EOF). Matching
/// is case-insensitive on the heading title so CLI callers can ask for
/// "numeric literals". Returns null when no heading matches — derive the
/// valid titles with `SectionIterator`, never from a hardcoded list.
pub fn extractSection(doc: []const u8, title: []const u8) ?[]const u8 {
    var it = SectionIterator{ .doc = doc };
    while (it.next()) |sec| {
        if (std.ascii.eqlIgnoreCase(sec.title, title)) return sec.body;
    }
    return null;
}

/// One `## ` section of a rendered reference: the bare heading title and
/// the full body slice (heading line included).
pub const Section = struct { title: []const u8, body: []const u8 };

/// Walk the `## ` headings of a rendered reference in order. Keeps the
/// section list derived from the generated output itself, so a new doc
/// section is automatically addressable with zero registration.
pub const SectionIterator = struct {
    doc: []const u8,
    pos: usize = 0,

    pub fn next(self: *SectionIterator) ?Section {
        const start = findHeading(self.doc, self.pos) orelse return null;
        const title_start = start + "## ".len;
        const title_end = std.mem.indexOfScalarPos(u8, self.doc, title_start, '\n') orelse self.doc.len;
        const end = findHeading(self.doc, title_end) orelse self.doc.len;
        self.pos = end;
        return .{
            .title = std.mem.trim(u8, self.doc[title_start..title_end], " \r"),
            .body = self.doc[start..end],
        };
    }

    /// Byte offset of the next line starting with `## `, at or after `from`.
    fn findHeading(doc: []const u8, from: usize) ?usize {
        var i = from;
        while (std.mem.indexOfPos(u8, doc, i, "## ")) |hit| {
            if (hit == 0 or doc[hit - 1] == '\n') return hit;
            i = hit + 1;
        }
        return null;
    }
};

/// Write table-cell content, escaping `|` so syntax templates like
/// `(status concept|implemented|review)` don't split the Markdown cell.
fn writeCell(writer: anytype, text: []const u8) !void {
    for (text) |c| {
        if (c == '|') try writer.writeAll("\\|") else try writer.writeByte(c);
    }
}

fn writeArity(writer: anytype, schema: ?forms.FormSchema) !void {
    const s = schema orelse {
        try writer.writeAll("—");
        return;
    };
    if (s.max_args) |max| {
        if (max == s.min_args) {
            try writer.print("{d}", .{s.min_args});
        } else {
            try writer.print("{d}–{d}", .{ s.min_args, max });
        }
    } else {
        try writer.print("{d}+", .{s.min_args});
    }
}

/// Power-of-ten exponent of an SI multiplier (all entries in
/// `tokenizer.si_scales` are exact powers of ten).
fn multiplierExponent(m: f64) i32 {
    return numeric.checkedInt(i32, @round(@log10(m))) orelse 0;
}

// ── Tests ──────────────────────────────────────────────────────────────

// spec: docgen - renderLanguageReference output matches the committed docs/language-forms.md so docs can never lag the registries
test "language-forms.md is in sync with the dispatch tables" {
    const alloc = std.testing.allocator;

    // Skip when the test is invoked outside a project tree (the file
    // simply isn't there to compare against) — the build's
    // `gen-language-docs --check` step still enforces presence + sync
    // with a deterministic cwd.
    const committed = infra_fs.cwd().readFileAlloc(alloc, "docs/language-forms.md", 1024 * 1024) catch return;
    defer alloc.free(committed);

    const generated = try renderLanguageReference(alloc);
    defer alloc.free(generated);

    // expectEqualStrings produces a usable diff on failure. To
    // regenerate the file, run `zig build docs`.
    try std.testing.expectEqualStrings(committed, generated);
}

// spec: docgen - extractSection returns one ## section of the rendered reference, matching the title case-insensitively
test "extractSection slices one heading's section" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    const sec = extractSection(doc, "numeric literals").?;
    try std.testing.expect(std.mem.startsWith(u8, sec, "## Numeric literals"));
    try std.testing.expect(std.mem.indexOf(u8, sec, "## Design-scope forms") == null);
    try std.testing.expect(extractSection(doc, "no such section") == null);
}

/// (helper) Count the `## ` sections an iterator yields.
fn countSections(doc: []const u8) usize {
    var it = SectionIterator{ .doc = doc };
    var n: usize = 0;
    while (it.next()) |_| n += 1;
    return n;
}

// spec: docgen - SectionIterator walks every ## heading of the rendered reference in order
test "SectionIterator finds the reference sections" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    var it = SectionIterator{ .doc = doc };
    const first = it.next().?;
    try std.testing.expectEqualStrings("Special forms", first.title);
    try std.testing.expect(countSections(doc) >= 6);
}

// spec: docgen - The generated reference names every category key so (category …) docs follow the classifier map
test "category keys section covers the classifier map" {
    // Every key in the classifier's `(category <key>)` map must be a
    // Category enum tag name — the doc section walks the enum, so an
    // alias key added only to the map would silently go undocumented.
    for (block_types.category_keys.keys()) |key| {
        try std.testing.expect(std.meta.stringToEnum(block_types.Category, key) != null);
    }
}

// spec: docgen - Every document the generated reference links to exists in docs/
test "the reference links only to documents that exist" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    // Sibling-document links are written as `](<name>.md)`; each must name a
    // file still in docs/. The header pointed at a deleted second grammar for
    // months, and nothing noticed.
    var i: usize = 0;
    var checked: usize = 0;
    while (std.mem.indexOfPos(u8, doc, i, "](")) |open| {
        const close = std.mem.indexOfPos(u8, doc, open, ")") orelse break;
        i = close + 1;
        const target = doc[open + 2 .. close];
        if (!std.mem.endsWith(u8, target, ".md")) continue;
        if (std.mem.indexOfScalar(u8, target, '/') != null) continue; // not a sibling
        const path = try std.fmt.allocPrint(alloc, "docs/{s}", .{target});
        defer alloc.free(path);
        infra_fs.cwd().access(path, .{}) catch |err| {
            std.debug.print("generated reference links to missing docs/{s}: {s}\n", .{ target, @errorName(err) });
            return error.TestUnexpectedResult;
        };
        checked += 1;
    }
    try std.testing.expect(checked >= 1);
    // The hand-written guide is docs/sexp-language.md; its former twin
    // sexpr-language.md is gone, so the header must name the survivor.
    try std.testing.expect(std.mem.indexOf(u8, doc, "](sexp-language.md)") != null);
    try std.testing.expect(std.mem.indexOf(u8, doc, "sexpr-language") == null);
}

// spec: docgen - The assert form's registry summary states that build and export-kicad fail on a failed assertion

test "assert summary states the build-fails rule" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);
    // The registry summary is what `netlisp reference` and the generated
    // table print; it once promised the opposite of what `build` does.
    try std.testing.expect(std.mem.indexOf(u8, doc, "never aborts the build") == null);
    try std.testing.expect(std.mem.indexOf(u8, doc, "write nothing and exit 1") != null);
}

// spec: docgen - The section-classifier reference states that an explicit (category …) is the source of truth
test "classifier section names (category …) as authoritative" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    const sec = extractSection(doc, "Section-name classifier keywords").?;
    // The name keywords are the FALLBACK; a reader must not come away thinking
    // the section title is what decides the category.
    try std.testing.expect(std.mem.indexOf(u8, sec, "source of\ntruth") != null);
    try std.testing.expect(std.mem.indexOf(u8, sec, "section_category_inferred") != null);
}

/// Whether the rendered "Review checks" section carries a heading for every
/// review category. Hoisted out of its test so the test keeps one loop.
fn everyCategoryHeadingPresent(section: []const u8) bool {
    for (std.enums.values(review_registry.Category)) |category| {
        if (std.mem.indexOf(u8, section, category.title()) == null) return false;
    }
    return true;
}

// spec: docgen - The generated reference has a Review checks section rendered from the review registry
test "review checks section covers every registered row" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    const sec = extractSection(doc, "Review checks").?;
    try std.testing.expect(std.mem.startsWith(u8, sec, "## Review checks"));
    // Every category heading and every registered id reaches the table.
    try std.testing.expect(everyCategoryHeadingPresent(sec));
    for (review_registry.rows) |row| {
        try std.testing.expect(std.mem.indexOf(u8, sec, row.id) != null);
        try std.testing.expect(std.mem.indexOf(u8, sec, row.asserts) != null);
    }
    try std.testing.expect(extractSection(doc, "review checks") != null);
}

// spec: docgen - The generated reference has a Requirement checks section rendered from the checker's check_docs table
test "requirement checks section covers every check form" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    const sec = extractSection(doc, "Requirement checks").?;
    try std.testing.expect(std.mem.startsWith(u8, sec, "## Requirement checks"));
    // Each row of the checker's own dispatch table must be documented here —
    // the summaries carry no `|`, so they survive verbatim into the cell.
    for (check_grammar.check_docs) |d| {
        try std.testing.expect(std.mem.indexOf(u8, sec, d.summary) != null);
    }
    // And the section is addressable by the CLI get_language_reference tool.
    try std.testing.expect(extractSection(doc, "requirement checks") != null);
}
// ── Reference coverage ─────────────────────────────────────────────────
// The registries above make the reference exhaustive over the head atoms the
// evaluator DISPATCHES on. They cannot see the head atoms it merely MATCHES
// on — `node.isForm("bridge")` deep inside a parser — and that is exactly
// where the reference used to go stale. The test below reads `src/eval` the
// way the tree actually is, pulls every `isForm("…")` literal out of it, and
// requires each name to be reachable from the generated reference.

/// One head atom `src/eval` matches on that is deliberately absent from the
/// reference, with the reason it stays that way. Keep this list empty unless
/// a name is genuinely internal — the point of the coverage test is that a
/// user-writable form cannot hide here without an argument for it.
const UndocumentedForm = struct { name: []const u8, why: []const u8 };

const undocumented_eval_forms = [_]UndocumentedForm{};

/// True when `name` is documented: a dispatch-registry head atom, a sub-form
/// registry row, or a form the generated reference names in a syntax template
/// (which is itself always rendered from a registry).
fn isCoveredForm(doc: []const u8, name: []const u8) bool {
    if (forms.SpecialForm.fromAtom(name) != null) return true;
    if (forms.ScopeForm.fromAtom(name) != null) return true;
    if (forms.isRegisteredSubForm(name)) return true;
    return referenceNamesForm(doc, name);
}

/// True when `name` is deliberately left out of the reference.
fn isDeliberatelyUndocumented(name: []const u8) bool {
    for (undocumented_eval_forms) |entry| {
        if (std.mem.eql(u8, entry.name, name)) return true;
    }
    return false;
}

/// True when the rendered reference writes `(<name>` as a head atom — the
/// name must end at the paren-word boundary, so `(rate` never satisfies
/// `rated` and `(id` never satisfies `ids`.
fn referenceNamesForm(doc: []const u8, name: []const u8) bool {
    var i: usize = 0;
    while (std.mem.indexOfScalarPos(u8, doc, i, '(')) |open| {
        i = open + 1;
        const rest = doc[i..];
        if (!std.mem.startsWith(u8, rest, name)) continue;
        const after = rest[name.len..];
        if (after.len == 0 or !isFormNameChar(after[0])) return true;
    }
    return false;
}

fn isFormNameChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or c == '-' or c == '_';
}

/// Append `<file>: (<name> …)` for every `isForm("…")` head atom in `source`
/// that no registry documents. Collecting rather than failing on the first hit
/// lets the test report the whole gap in one failure.
fn collectUncoveredForms(
    alloc: std.mem.Allocator,
    doc: []const u8,
    file: []const u8,
    source: []const u8,
    out: *std.ArrayList(u8),
) !void {
    const marker = "isForm(\"";
    var rest = source;
    while (std.mem.indexOf(u8, rest, marker)) |hit| {
        const start = hit + marker.len;
        const end = std.mem.indexOfScalarPos(u8, rest, start, '"') orelse return;
        const name = rest[start..end];
        rest = rest[end..];
        if (!isPlausibleFormName(name)) continue;
        if (isCoveredForm(doc, name) or isDeliberatelyUndocumented(name)) continue;
        try out.print(alloc, "{s}: ({s} …) is documented by no registry\n", .{ file, name });
    }
}

/// True when every byte could belong to a head atom, so the scan skips the
/// `isForm("…")` that appears inside prose in a doc comment.
fn isPlausibleFormName(name: []const u8) bool {
    if (name.len == 0) return false;
    for (name) |c| {
        if (!isFormNameChar(c)) return false;
    }
    return true;
}

// spec: docgen - Every isForm head atom under src/eval is reachable from a form registry or listed as a deliberate exception
test "the reference covers every form head the evaluator matches on" {
    const alloc = std.testing.allocator;

    // Skip outside a project tree, exactly as the sync test above does; the
    // build's docs-check step runs with a deterministic cwd.
    var dir = infra_fs.cwd().openDir("src/eval", .{ .iterate = true }) catch return;
    defer dir.close();

    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    var uncovered: std.ArrayList(u8) = .empty;
    defer uncovered.deinit(alloc);

    var it = dir.iterate();
    while (try it.next()) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".zig")) continue;
        const source = try dir.readFileAlloc(alloc, entry.name, 4 * 1024 * 1024);
        defer alloc.free(source);
        try collectUncoveredForms(alloc, doc, entry.name, source, &uncovered);
    }

    // Any listed name needs a row in src/eval/forms.zig — or, when it is truly
    // internal, an entry in `undocumented_eval_forms` with its reason.
    try std.testing.expectEqualStrings("", uncovered.items);
}

// spec: docgen - The generated reference renders one sub-form section per compound-form registry
test "sub-form sections render every registry row" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    // `(bridge …)` is the form that was in neither doc before these sections.
    const sub_block = extractSection(doc, "Sub-block sub-forms").?;
    try std.testing.expect(std.mem.indexOf(u8, sub_block, "(bridge \"PREFIX\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, sub_block, "(rename PORT SUFFIX)") != null);

    // Every row of every registry reaches the page it belongs to.
    for (forms.sub_form_tables) |table| {
        for (table) |row| try std.testing.expect(std.mem.indexOf(u8, doc, row.summary) != null);
    }
    try std.testing.expect(extractSection(doc, "instance sub-forms") != null);
}
