//! Test-suite shard manifest: which unit tests each parallel `zig build test`
//! binary runs.
//!
//! `zig build test` compiles one test binary PER SHARD and runs them
//! concurrently (the build system runs independent steps in parallel). Every
//! binary is built from the same `src/test_root.zig` module, the same optimize
//! mode and the same Guardian test runner; the only difference is the
//! `--test-filter` set the compiler applies, which is exactly the list below.
//!
//! Each entry is a literal `--test-filter` substring, matched by the COMPILER
//! against the fully-qualified test name (`<dotted source path>.test.<name>`).
//! Two forms are used:
//!
//!   "placement.drc.test."       — every named test in `src/placement/drc.zig`
//!   "placement.router.test.con" — the tests in `src/placement/router.zig`
//!                                 whose names start with `con`
//!
//! The second form exists only for files too expensive to keep whole:
//! `placement/router.zig` alone is 30.8s of a 78.0s serial suite, so no
//! file-granular split can beat it. Splitting on a fixed-length name prefix
//! keeps the entries stable under everything except a rename that changes a
//! test's first three characters — and that rename fails the coverage test in
//! `src/test_root.zig` loudly instead of silently dropping the test.
//!
//! Substring matching has no anchor, so `"exit.test."` also selects
//! `placement.pad_exit.test.*`; atoms that cannot be separated that way are
//! packed into the same shard rather than being renamed.
//!
//! INVARIANTS, all enforced by tests in `src/test_root.zig` rather than by
//! this file's good intentions:
//!
//!   * every named test in src/ is claimed by exactly ONE shard;
//!   * every filter here still names a test;
//!   * every test a shard claims is actually IN that shard's compiled binary
//!     (an unnamed `test` block runs the check inside each shard — a filter
//!     naming a test the compiler never analyzed would otherwise vanish
//!     silently, which is how the first sharded build lost 49 tests while all
//!     eight shards reported PASS).
//!
//! Unnamed `test { _ = @import(...) }` blocks are NOT listed: the compiler
//! links them into every filtered binary regardless of the filters, so each
//! shard runs all of them. They are import bridges with empty bodies, so the
//! duplicate cost is nil; it is why the shard test counts sum to more than the
//! whole suite's count.
//!
//! Balance is by MEASURED wall time, not test count. Regenerate with
//! `scripts/test_shard_balance.py` after a large shift in test cost.

const std = @import("std");

pub const shards: []const []const []const u8 = &.{
    // shard 0
    &.{
        "ground_via_seed.test.",
        "placement.fine_accept.test.a n",
        "serve.ground_vias.test.",
        "serve.pcb_step_export.test.",
        "infra.source_transaction.test.",
        "serve.edit_request.test.",
        "serve.edit_target.test.",
        "serve.edit_contract_tests.test.",
        "serve.system_cad.test.",
        "mechanical.prismatic.test.",
        "mechanical.enclosure.test.",
        "mechanical.cad_document.test.",
        "bench_page.test.",
        "placement.fill_cache.test.",
        "placement.content_key.test.",
        "drc_dump.test.",
        "power_flow_cli.test.",
        "gerber_dump.test.",
        "netlist_dump.test.",
        "pins_by_name.test.",
        "drc_reconcile.test.",
        "drc_sweep.test.",
        "placement.drc_compose.test.",
        "placement.drc_scope.test.",
        "placement.drc_pour.test.",
        "placement.rf_pad_adapt.test.",
        "fab_gate.test.",
        "fab_package.test.",
        "fab_release.test.",
        "fab_schematic_gate.test.",
        "design_archive.test.",
        "deploy_unit.test.",
        "infra.atomic_write.test.",
        "infra.fs.test.",
        "infra.process_alloc.test.",
        "layout_sidecar_store.test.",
        "main.test.",
        "panelize.test.",
        "serve.panel_export.test.",
    },
    // shard 1
    &.{
        "authored_heatsink.test.",
        "bom_resolve.test.",
        "component_classification.test.",
        "convert.footprint.test.",
        "convert.symbol.test.",
        "decouple_key.test.",
        "drc_session.test.",
        "drc_board_json.test.",
        "emit.test.",
        "elmer_thermal_command.test.",
        "eval.design_block.test.",
        "eval.electrical.test.",
        "eval.env.test.",
        "eval.instance.test.",
        "export_elmer_thermal.test.",
        "export_matlab_rf.test.",
        "import_fold_emit.test.",
        "import_kicad.test.",
        "frequency_plan.test.",
        "kicad_pcb.route_score.test.",
        "kicad_pcb.router_adapter.test.",
        "kicad_pcb.snapshot.test.",
        "kicad_sch.emit.test.",
        "kicad_sch.glyph.test.",
        "kicad_sch.plan.test.",
        "kicad_sch.stub.test.",
        "placement.cdt_layers.test.",
        "placement.cdt_route.test.",
        "placement.copper_topology_route_regression.test.",
        "placement.diff_shape.test.",
        "placement.drc.test.",
        "placement.drc_power_width.test.",
        "placement.fine_window.test.",
        "placement.geometry.test.",
        "placement.layout_lint.test.",
        "placement.maze_scratch.test.",
        "placement.module_policy.test.",
        "placement.net_topology_route_regression.test.",
        "placement.pad_entry.test.",
        "placement.pad_neck.test.",
        "placement.path_copper.test.",
        "placement.variable_width_copper.test.",
        "placement.detour_route_regression.test.",
        "placement.ldo_route_quality_regression.test.",
        "placement.plane_stitch_route_regression.test.",
        "placement.rf_port_frames.test.",
        "placement.rough_identity.test.",
        "placement.route_shape_score.test.",
        "placement.router.test.con",
        "placement.router.test.imm",
        "placement.router.test.net",
        "placement.shove.test.",
        "placement.topo_plan.test.a g",
        "placement.topo_plan.test.a w",
        "placement.topo_plan.test.pla",
        "placement.via_antipad.test.",
        "placement.via_centre.test.",
        "placement.via_fence.test.",
        "pll_loop.test.",
        "spurious.test.",
        "raster.test.",
        "render_json.test.",
        "render_order.test.",
        "render_svg.section_inset.test.",
        "req_checks_cases.test.",
        "req_physical_checks_cases.test.",
        "serve.diag_format.test.",
        "serve.gzip_cache.test.",
        "serve.history.test.",
        "serve.layer_table_json.test.",
        "serve.layout_sidecar_json.test.",
        "serve.mcp_placement_sensitivity.test.",
        "serve.mcp_route_trials.test.",
        "serve.mcp_schematic_view.test.",
        "serve.pour_json.test.",
        "serve.request_log.test.",
        "layout_save_layers.test.",
    },
    // shard 2
    &.{
        "build_id.test.",
        "canonical_module_check.test.",
        "commands.test.",
        "convert.alt_functions.test.",
        "eval.modules.test.",
        "eval.net_analysis.test.",
        "fab_preview.test.",
        "json_writer.test.",
        "kicad_pcb.experiment.test.",
        "kicad_pcb.inspect.test.",
        "kicad_pcb.writer.test.",
        "kicad_sch.compose.test.",
        "kicad_sch.gang.test.",
        "kicad_sch.shape.test.",
        "kicad_sch.sheet.test.",
        "kicad_sch.stagger.test.",
        "kicad_sch.textbox.test.",
        "kicad_sch.verify.test.",
        "kicad_sch.wire.test.",
        "kicad_sym.library.test.",
        "layout_status.test.",
        "leak_tests.serve_stores.test.",
        "placement.airwire_geometry.test.",
        "placement.connector_pinout.test.",
        "placement.drc_diffpair.test.",
        "placement.escape_assign.test.",
        "placement.fine_accept.test.the",
        "placement.elliptic_integral.test.",
        "placement.impedance.test.",
        "placement.impedance_field.test.",
        "placement.lane_reserve.test.",
        "placement.net_rules.test.",
        "placement.pour.test.",
        "placement.pour_patch_regression.test.",
        "placement.power_branch_width.test.",
        "placement.power_capacity.test.",
        "placement.power_integrity.test.",
        "placement.pdn_impedance.test.",
        "placement.power_current.test.",
        "power_integrity_json.test.",
        "placement.rf_port_finish.test.",
        "placement.rough_routability.test.",
        "placement.route_grid.test.",
        "placement.route_session.test.stu",
        "placement.router.test.a p",
        "placement.router.test.a t",
        "placement.router.test.esc",
        "placement.router.test.exp",
        "placement.router.test.gap",
        "placement.router.test.one",
        "placement.router.test.pla",
        "placement.router.test.qua",
        "placement.topo_plan.test.a l",
        "placement.trace_em.test.",
        "preflight.test.",
        "board_review_catalog.test.",
        "board_review_state.test.",
        "review_assessment.test.",
        "review_datasheet_inventory.test.",
        "review_audit.test.",
        "review_profiles.test.",
        "waiver_register.test.",
        "render_svg.draw.test.",
        "review.test.",
        "serve.board_backup.test.",
        "serve.component_info.test.",
        "serve.datasheet.test.",
        "serve.design_rules_edit.test.",
        "serve.edit_assist.test.",
        "serve.footprint_preview.test.",
        "serve.mcp_arg_names.test.",
        "serve.mcp_checks.test.",
        "serve.mcp_connector_pinout.test.",
        "serve.route_live.test.",
        "serve.route_review.test.",
        "serve.test.",
        "silk_font.test.",
        "zipfile.test.",
    },
    // shard 3
    &.{
        "bench_route.test.",
        "eval.check_grammar.test.",
        "eval.evaluator.test.",
        "eval.forms.test.",
        "eval.ids.test.",
        "export_kicad_netlist.test.",
        "export_pdf.test.",
        "fab_identity.test.",
        "flat_netlist.test.",
        "id_insert.test.",
        "kicad_pcb.format.test.",
        "kicad_pcb.import_layout.test.",
        "kicad_pcb.reference_guides.test.",
        "lib_limits.test.",
        "stdlib.test.",
        "net_name.test.",
        "numeric.test.",
        "shape_sketch.test.",
        "pdf.test.",
        "placement.critical_route_score.test.",
        "placement.diff_pairs.test.",
        "placement.drc_perimeter_keepout.test.",
        "placement.drc_board_keepout.test.",
        "placement.drc_return_path.test.",
        "placement.octilinear.test.",
        "placement.pin_roles.test.",
        "placement.plane_via.test.",
        "placement.progress.test.",
        "placement.rf_shadow.test.",
        "placement.route_session.test.non",
        "placement.route_timing.test.",
        "placement.routed_copper.test.",
        "placement.router.test.Oct",
        "placement.router.test.a f",
        "placement.router.test.a m",
        "placement.router.test.a v",
        "placement.router.test.a g",
        "placement.router.test.an ",
        "placement.router.test.dij",
        "placement.router.test.hig",
        "placement.topo_plan.test.dem",
        "placement.via_merge.test.",
        "render_html.test.",
        "render_svg.schematic_walk.test.",
        "render_svg.branch.test.",
        "serve.assembly_debug.test.",
        "serve.assembly_page_cache.test.",
        "serve.auth_store.test.",
        "serve.footprint_editor.test.",
        "serve.layout_layers.test.",
        "serve.mcp_escape_assign.test.",
        "serve.mcp_parts_tools.test.",
        "serve.mcp_read_opts.test.",
        "serve.mcp_route_experiment.test.",
        "serve.notes.test.",
        "serve.shape_sketch_json.test.",
        "serve.pcb_layout_page.test.",
        "serve.pcb_subseeds.test.",
        "serve.pcb_page_cache.test.",
        "serve.pcb_derived.test.",
        "serve.progress_cache.test.",
        "serve.describe_cache.test.",
        "serve.cache_core.test.",
        "serve.page_cache_endpoint.test.",
        "serve.read_cache.test.",
        "serve.png_cache.test.",
        "serve.route_plan.test.",
        "serve.route_session_api.test.",
        "serve.route_vision.test.",
        "serve.schematic_pdf.test.",
        "serve.thermal_api.test.",
        "serve.thermal_cache.test.",
        "serve.thermal_page.test.",
        "serve.urlcodec.test.",
        "serve.subprocess.test.",
        "serve.sync_kicad_sch.test.",
        "serve.upload_datasheet.test.",
        "serve.vfs.test.",
        "sexpr.paren_span.test.",
        "sexpr.parser.test.",
        "sexpr.printer.test.",
        "svg2pdf.test.",
        "wasm_drc.test.",
    },
    // shard 4
    &.{
        "board_layers.test.",
        "board_theme.test.",
        "config.test.",
        "diagram.classify.test.",
        "diagram.lod.test.",
        "docgen.test.",
        "eval.micro_forms.test.",
        "eval.power_sequencing.test.",
        "eval.stackup_presets.test.",
        "exit.test.",
        "fab_readiness.test.",
        "route_cleanup_gate.test.",
        "route_repair.test.",
        "route_resume.test.",
        "kicad_pcb.import_layout_command.test.",
        "kicad_pcb.net_aliases.test.",
        "leak_tests.placement.test.",
        "leak_tests.render.test.",
        "module_metadata.test.",
        "pad_neck_shape.test.",
        "placement.bypass_intent.test.",
        "placement.bypass_open.test.",
        "placement.congestion.test.",
        "placement.copper_topology.test.",
        "placement.courtyard_close.test.",
        "placement.diff_couple.test.",
        "placement.diff_direct.test.",
        "placement.diff_route.test.",
        "placement.drc_keepout.test.",
        "placement.drc_match.test.",
        "placement.drc_power_via.test.",
        "placement.impedance_coupled_microstrip.test.",
        "placement.impedance_coupled_stripline.test.",
        "placement.impedance_microstrip.test.",
        "placement.pad_exit.test.",
        "placement.pad_grid.test.",
        "placement.perimeter_fence.test.",
        "placement.plan_resolve.test.",
        "placement.pose_snapshot.test.",
        "placement.routability_lint.test.",
        "placement.pair_pinch.test.",
        "placement.pinch_probe.test.",
        "placement.place_repair.test.",
        "placement.route_close.test.",
        "placement.route_session.test.aba",
        "placement.router.test.a r",
        "placement.router.test.bat",
        "placement.router.test.cop",
        "placement.router.test.exc",
        "placement.router.test.fai",
        "placement.router.test.rf ",
        "placement.router.test.sam",
        "placement.router.test.seg",
        "placement.router.test.the",
        "placement.router_vision_regression.test.",
        "placement.topo_plan.test.a p",
        "placement.vacate_policy.test.",
        "serve.component_search.test.",
        "serve.datasheet_attach.test.",
        "serve.design_diff.test.",
        "serve.mcp_import_tools.test.",
        "serve.page_cache.test.",
        "serve.pcb_keepout_json.test.",
        "serve.rework_guide.test.",
        "serve.route_analyze_api.test.",
        "serve.schematic_page.test.",
        "serve.schematic_viewer_js.test.",
        "serve.auth.test.",
        "serve.ward_auth.test.",
        "serve.sync.test.",
        "serve.warmup.test.",
        "serve.warm_sched.test.",
    },
    // shard 5
    &.{
        "coverage.test.",
        "diagram.collect.test.",
        "diagram.layout.test.",
        "eval.board_role_cases.test.",
        "eval.board_keepout.test.",
        "eval.builders.test.",
        "eval.section_maturity.test.",
        "eval.power_budget.test.",
        "eval.test_point.test.",
        "eval.thermal.test.",
        "export_fab.test.",
        "export_gerber.test.",
        "export_kicad_footprint.test.",
        "font5x7.test.",
        "kicad_pcb.route_command.test.",
        "kicad_sch.bank.test.",
        "kicad_sym.reader.test.",
        "leak_tests.diagram.test.",
        "leak_tests.import_export.test.",
        "leak_tests.sexpr.test.",
        "pdf_afm.test.",
        "pdf_verify.test.",
        "placement.blocker_nomination.test.",
        "placement.cap_bind.test.",
        "placement.copper_contact.test.",
        "placement.copper_support.test.",
        "placement.critical_rough.test.",
        "placement.dive_elide.test.",
        "placement.via_hop_scan.test.",
        "placement.net_rewrite_pass.test.",
        "placement.escalate_retry.test.",
        "placement.gap_close_route.test.",
        "placement.gap_policy.test.",
        "placement.impedance_cache.test.",
        "placement.impedance_rules.test.",
        "placement.keepout.test.",
        "placement.keepout_route.test.",
        "placement.manhattan_route.test.",
        "placement.near_bind.test.",
        "placement.optimizer.test.",
        "placement.plane_stitch.test.",
        "placement.route_cleanup.test.",
        "placement.route_policy.test.",
        "placement.router.test.A s",
        "placement.router.test.bud",
        "placement.router.test.clo",
        "placement.router.test.dif",
        "placement.router.test.out",
        "placement.topo_plan.test.a s",
        "placement.topo_plan.test.two",
        "png.test.",
        "render_pcb_png.test.",
        "render_thermal_png.test.",
        "render_schematic_png.test.",
        "render_svg.hub.test.",
        "serve.edit.test.",
        "serve.api.test.",
        "serve.kicad_sch_export.test.",
        "serve.layout_backfill.test.",
        "serve.library.test.",
        "serve.datasheet_ref.test.",
        "serve.design_archive_api.test.",
        "serve.mcp_close_gaps.test.",
        "serve.mcp_kicad_sch.test.",
        "serve.mcp_route_order.test.",
        "serve.mcp_tools.test.",
        "serve.pcb_layout_import.test.",
        "serve.pcb_progress.test.",
        "serve.placement_outline.test.",
        "test_root.test.",
        "testpoint_silkscreen.test.",
        "tool_cli.test.",
    },
    // shard 6
    &.{
        "deflate.test.",
        "diagram.membership.test.",
        "diagram.render.test.",
        "diagram.system_of_boards.test.",
        "escape.test.",
        "eval.builtins.test.",
        "eval.fmt.test.",
        "eval.pin_enrichment.test.",
        "eval.validate.test.",
        "githash.test.",
        "infra.random.test.",
        "kicad_pcb.project_rules.test.",
        "kicad_pcb.reader.test.",
        "kicad_sch.project.test.",
        "leak_tests.checks.test.",
        "leak_tests.serve_auth_request.test.",
        "leak_tests.serve_ward_request.test.",
        "leak_tests.serve_request.test.",
        "placement.copper_length.test.",
        "placement.guide_branch.test.",
        "placement.implicit_plane.test.",
        "placement.island_accept.test.",
        "placement.land_transit.test.",
        "placement.net_identity.test.",
        "placement.net_graph.test.",
        "placement.net_open.test.",
        "placement.net_topology.test.",
        "placement.outline.test.",
        "placement.pad_escape.test.",
        "placement.port_escape.test.",
        "placement.rf_path_solver.test.",
        "placement.route_diagnose.test.",
        "placement.route_score.test.",
        "placement.route_session.test.a c",
        "placement.route_session.test.acc",
        "placement.router.test.a c",
        "placement.router.test.a d",
        "placement.router.test.any",
        "placement.router.test.per",
        "placement.router.test.pow",
        "placement.router.test.rip",
        "placement.router.test.via",
        "placement.straighten.test.",
        "placement.thermal_field.test.",
        "placement.topo_plan.test.a t",
        "render_svg.connection.test.",
        "serve.autocommit.test.",
        "serve.bom_html.test.",
        "serve.digikey.test.",
        "serve.drc_json.test.",
        "serve.drc_rules.test.",
        "serve.fab_filename.test.",
        "serve.layout_backfill_command.test.",
        "serve.layout_merge_command.test.",
        "serve.library_3d.test.",
        "serve.mcp_flatten.test.",
        "serve.modules.test.",
        "serve.navbar.test.",
        "serve.pages.test.",
        "serve.pcb_fence.test.",
        "serve.pcb_layout_sync.test.",
        "serve.pcb_rules_json.test.",
        "serve.rough_best.test.",
        "serve.stuck_json.test.",
        "serve.twin_parity.test.",
        "sexpr.ast.test.",
        "sexpr.tokenizer.test.",
        "target_unblock.test.",
    },
    // shard 7
    &.{
        "uuid.test.",
        "bom.test.",
        "erc.test.",
        "eval.net_envelopes.test.",
        "eval.rails.test.",
        "eval.net_suggest.test.",
        "eval.suggest.test.",
        "eval.value_kind.test.",
        "eval.footprint_pads.test.",
        "export_kicad.test.",
        "export_kicad_sch.test.",
        "gerber_verify.test.",
        "import_fold.test.",
        "kicad_pcb.import_layout_json.test.",
        "kicad_sch.vendor.test.",
        "kicad_sch_push.test.",
        "leak_tests.eval_core.test.",
        "leak_tests.review_bom.test.",
        "parts.test.",
        "paths.test.",
        "placement.bend_smooth.test.",
        "placement.critical_paths.test.",
        "placement.edge_rotation.test.",
        "placement.joint_rescue.test.",
        "placement.mask_relief.test.",
        "placement.match_group.test.",
        "poly_scanline.test.",
        "placement.pad_shape.test.",
        "placement.pad_project.test.",
        "placement.pad_world.test.",
        "placement.disc_stamp.test.",
        "placement.pose_math.test.",
        "placement.route_determinism.test.",
        "placement.route_free_space.test.",
        "placement.route_session.test.a r",
        "placement.route_session.test.sta",
        "placement.route_space_cache.test.",
        "placement.router.test.Loo",
        "placement.router.test.a k",
        "placement.router.test.a s",
        "placement.router.test.pad",
        "placement.router.test.ret",
        "placement.router.test.rou",
        "placement.router.test.sco",
        "placement.router.test.str",
        "placement.router.test.tri",
        "placement.router.test.wel",
        "placement.router_via_rules.test.",
        "placement.router_waypoint_regression.test.",
        "placement.topo_lower.test.",
        "placement.topo_plan.test.a c",
        "placement.via_guide.test.",
        "refdes_stability.test.",
        "render_svg.context.test.",
        "req_derived_checks.test.",
        "review_md.test.",
        "system_review_assets.test.",
        "system_review_html.test.",
        "system_review_md.test.",
        "system_review_package.test.",
        "board_review_snapshot.test.",
        "serve.fab_release_service.test.",
        "serve.dossier_jobs.test.",
        "serve.system_review_api.test.",
        "review_thermal.test.",
        "thermal_scenarios.test.",
        "serve.layout_match.test.",
        "serve.mcp_routability.test.",
        "serve.pcb_describe.test.",
        "serve.pcb_part_json.test.",
        "serve.pose_identity.test.",
        "serve.rate_limiter.test.",
        "serve.route_result_stats.test.",
        "serve.saved_anchor_migration.test.",
        "serve.static_assets.test.",
        "serve.style_score.test.",
        "serve.subcircuit_route.test.",
        "serve.upload.test.",
        "serve.upload_package.test.",
        "subcircuit_route_regression.test.",
        "subcircuit_seed_drc.test.",
        "subcircuit_silkscreen.test.",
    },
};

// spec: Development pipeline - Ground-via seed model and endpoint tests remain claimed by the shard manifest
test {
    try std.testing.expectEqualStrings("ground_via_seed.test.", shards[0][0]);
    try std.testing.expectEqualStrings("serve.ground_vias.test.", shards[0][2]);
    try std.testing.expectEqualStrings("serve.pcb_step_export.test.", shards[0][3]);
}

// spec: Development pipeline - Panelization export tests remain claimed by the shard manifest
test {
    var claimed = false;
    for (shards[0]) |filter| {
        if (std.mem.eql(u8, filter, "panelize.test.")) claimed = true;
    }
    try std.testing.expect(claimed);
}

// spec: Development pipeline - RF pad adaptation tests remain claimed by the shard manifest
test {
    var claimed = false;
    for (shards[0]) |filter| {
        if (std.mem.eql(u8, filter, "placement.rf_pad_adapt.test.")) claimed = true;
    }
    try std.testing.expect(claimed);
}

// spec: Development pipeline - The live sub-circuit Stamp endpoint regression remains claimed by the shard manifest
test {
    var claimed = false;
    for (shards[3]) |filter| {
        if (std.mem.eql(u8, filter, "serve.pcb_subseeds.test.")) claimed = true;
    }
    try std.testing.expect(claimed);
}

// spec: Development pipeline - The saved-pose identity tests remain claimed by the shard manifest
test {
    var claims: usize = 0;
    for (shards) |shard| {
        for (shard) |filter| {
            if (std.mem.eql(u8, filter, "serve.pose_identity.test.")) claims += 1;
        }
    }
    try std.testing.expectEqual(@as(usize, 1), claims);
}
