//! Physical copper identity for evaluator-generated per-pin bypass nets.
//!
//! `(decouple ... per-pin ...)` deliberately splits one logical rail into a
//! `<rail>.<IC>.<pad>` connection net so placement and routing retain the exact
//! bypass target.  On the fabricated board that connection is still the parent
//! rail: parent-rail copper may land on the cap and IC pads.  This module is the
//! narrow proof used by physical checks to recognize that relationship without
//! guessing from punctuation alone.

const std = @import("std");
const net_name = @import("../net_name.zig");
const optimizer = @import("optimizer.zig");

/// Canonical physical owner for every flattened net index on one placement.
pub const Identity = struct {
    /// Index-aligned canonical owner; empty means exact identity only.
    owner: []const i32 = &.{},

    /// Prove and record every explicit generated bypass-stub → parent alias.
    pub fn init(arena: std.mem.Allocator, placement: optimizer.Placement) std.mem.Allocator.Error!Identity {
        const owners = try arena.alloc(i32, placement.nets.len);
        for (owners, 0..) |*slot, i| slot.* = @intCast(i);

        for (placement.loops) |loop| {
            if (loop.pwr_net < 0 or loop.explicit_pin.len == 0) continue;
            const stub_i: usize = @intCast(loop.pwr_net);
            if (stub_i >= placement.nets.len or loop.cap >= placement.parts.len or loop.hub >= placement.parts.len) continue;

            const split_name = split(placement.nets[stub_i].name) orelse continue;
            const hub = placement.parts[loop.hub];
            if (!std.mem.eql(u8, split_name.ref, net_name.leaf(hub.ref_des))) continue;
            if (!std.mem.eql(u8, split_name.pad, loop.explicit_pin)) continue;
            if (!hasPin(placement.nets[stub_i], hub.ref_des, loop.explicit_pin)) continue;

            const cap = placement.parts[loop.cap];
            const cap_pin = padNumberAt(cap, loop.cap_pwr) orelse continue;
            if (!hasPin(placement.nets[stub_i], cap.ref_des, cap_pin)) continue;

            const base_i = findNet(placement.nets, split_name.base) orelse continue;
            owners[stub_i] = @intCast(base_i);
        }
        return .{ .owner = owners };
    }

    /// `-1` remains "no net" and never aliases another unnetted feature.
    pub fn same(self: Identity, a: i32, b: i32) bool {
        if (a < 0 or b < 0) return false;
        return self.canonical(a) == self.canonical(b);
    }

    /// Return the physical owner index, preserving invalid/unlisted indices.
    pub fn canonical(self: Identity, net: i32) i32 {
        if (net < 0) return net;
        const i: usize = @intCast(net);
        return if (i < self.owner.len) self.owner[i] else net;
    }

    /// Return the physical owner's flattened name, or empty for an invalid net.
    pub fn canonicalName(self: Identity, nets: []const optimizer.FlatNet, net: i32) []const u8 {
        const canonical_i = self.canonical(net);
        if (canonical_i < 0) return "";
        const i: usize = @intCast(canonical_i);
        return if (i < nets.len) nets[i].name else "";
    }
};

const Split = struct { base: []const u8, ref: []const u8, pad: []const u8 };

fn split(name: []const u8) ?Split {
    const last = std.mem.lastIndexOfScalar(u8, name, '.') orelse return null;
    if (last == 0 or last + 1 == name.len) return null;
    const prior = std.mem.lastIndexOfScalar(u8, name[0..last], '.') orelse return null;
    if (prior == 0 or prior + 1 == last) return null;
    return .{ .base = name[0..prior], .ref = name[prior + 1 .. last], .pad = name[last + 1 ..] };
}

fn findNet(nets: []const optimizer.FlatNet, name: []const u8) ?usize {
    for (nets, 0..) |net, i| if (std.mem.eql(u8, net.name, name)) return i;
    return null;
}

fn hasPin(net: optimizer.FlatNet, ref_des: []const u8, pin: []const u8) bool {
    for (net.pins) |candidate| {
        if (std.mem.eql(u8, candidate.ref_des, ref_des) and std.mem.eql(u8, candidate.pin, pin)) return true;
    }
    return false;
}

fn padNumberAt(part: optimizer.Part, rect: optimizer.PadRect) ?[]const u8 {
    if (!(rect.w > 0 and rect.h > 0)) return null;
    for (part.pads) |pad| {
        if (@abs(pad.x - rect.x) <= 1e-7 and @abs(pad.y - rect.y) <= 1e-7 and
            @abs(pad.w - rect.w) <= 1e-7 and @abs(pad.h - rect.h) <= 1e-7)
            return pad.number;
    }
    return null;
}

// spec: placement/physical-net-identity - Generated per-pin bypass connection nets share fabricated copper with their parent rail
// spec: placement/physical-net-identity - Dotted net names without matching explicit bypass-loop and pin evidence remain electrically distinct
test "only a structurally proven bypass connection aliases its parent rail" {
    const G = @import("geometry.zig");
    var arena_i = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_i.deinit();
    const arena = arena_i.allocator();

    const hub_pads = [_]G.Pad{.{ .number = "5", .x = 0, .y = 0, .w = 0.5, .h = 0.5 }};
    const cap_pads = [_]G.Pad{.{ .number = "1", .x = 0, .y = 0, .w = 0.5, .h = 0.5 }};
    var parts = [_]optimizer.Part{
        .{ .ref_des = "core/U1", .kind = .hub, .hw = 1, .hh = 1, .pads = &hub_pads, .fallback = false },
        .{ .ref_des = "core/C1", .kind = .passive, .hw = 1, .hh = 1, .pads = &cap_pads, .fallback = false },
    };
    const FlatPin = @import("../flat_netlist.zig").FlatPin;
    const stub_pins = [_]FlatPin{
        .{ .ref_des = "core/U1", .pin = "5" },
        .{ .ref_des = "core/C1", .pin = "1" },
    };
    const lookalike_pins = [_]FlatPin{
        .{ .ref_des = "core/U1", .pin = "6" },
        .{ .ref_des = "core/C1", .pin = "1" },
    };
    const nets = [_]optimizer.FlatNet{
        .{ .name = "core/VDD", .pins = &.{} },
        .{ .name = "core/VDD.U1.5", .pins = &stub_pins },
        .{ .name = "core/VDD.U1.6", .pins = &lookalike_pins },
        .{ .name = "SENSOR.DATA.1", .pins = &.{} },
    };
    const loops = [_]optimizer.Loop{.{
        .cap = 1,
        .hub = 0,
        .cap_pwr = .{ .x = 0, .y = 0, .w = 0.5, .h = 0.5 },
        .cap_gnd = .{ .x = 0, .y = 0, .w = 0.5, .h = 0.5 },
        .hub_pwr = &.{},
        .hub_pwr_pin = .{ .x = 0, .y = 0, .w = 0.5, .h = 0.5 },
        .hub_gnd = &.{},
        .pwr_net = 1,
        .explicit_pin = "5",
    }};
    const placement = optimizer.Placement{
        .parts = &parts,
        .links = &.{},
        .loops = &loops,
        .stubs = &.{},
        .instances = &.{},
        .nets = &nets,
        .score = .{ .hpwl_mm = 0, .loop_mm = 0, .loop_caps = 0 },
        .minx = 0,
        .miny = 0,
        .maxx = 1,
        .maxy = 1,
        .generated = false,
    };
    const identity = try Identity.init(arena, placement);
    try std.testing.expect(identity.same(0, 1));
    try std.testing.expect(!identity.same(0, 2));
    try std.testing.expect(!identity.same(0, 3));
    try std.testing.expect(!identity.same(-1, -1));
}
