//! One pad list, projected into the two views the rest of the board engine
//! reads it through.
//!
//! Three modules each carry their own world pad list — `drc.zig` (`PadBox`,
//! joined to nets from the placement), `router.zig` (`PadObs`, the maze's
//! obstacle set) and `drc_session.zig` (`PadLite`, the client probe session's) —
//! because each needs fields the others do not. What they do NOT need is three
//! copies of the projection into `keepout.PadPt` and `copper_topology.Terminal`:
//! those two shapes are owned by the modules that consume them, and a
//! projection that drops one of their fields is a silent behaviour change in
//! the consumer, not in the projector.
//!
//! They were three copies (four counting `topologyTerminals`, written twice
//! under one name in `drc.zig` and `route_cleanup.zig`), and the copies had
//! already drifted apart on `npth` and on net canonicalisation. Both survivals
//! are preserved and named below — a difference with a reason keeps it, and a
//! difference with none is gone.
//!
//! `pads` is `anytype` rather than a shared struct on purpose: making the three
//! owners agree on ONE pad type means moving `part`, `num`, `drill_oval` and
//! the slot half-vector into a struct two of the three never read. The
//! projections need six field names, every owner spells them the same, and a
//! missing one is a compile error at the call site.

const std = @import("std");
const keepout = @import("keepout.zig");
const copper_topology = @import("copper_topology.zig");
const net_identity = @import("net_identity.zig");

/// Does pad `p` GUARD copper — i.e. carry a real net's exact shape into the
/// keepout rule — or only contribute an escape terminal?
///
/// Unnetted copper never guards: a halo is declared by a `(net-class …)`, so a
/// pad on no net can own none. `npth` is the drifted half: `drc.zig`'s pad list
/// carries the flag and excludes a non-plated mounting hole (it has no copper
/// to protect), while the router's obstacle list has no such field at all —
/// every entry there is real copper the maze must avoid. Reading it only where
/// it exists keeps both call sites exactly as they behave today.
fn guards(comptime Pad: type, p: Pad) bool {
    if (p.net < 0) return false;
    return if (@hasField(Pad, "npth")) !p.npth else true;
}

/// Project a world pad list into the `(net, centre, guarded copper)` form the
/// RF keepout rule reads — the escape gate's terminals for every pad, plus the
/// exact copper shape for the ones that guard.
///
/// The DRC finding, the maze's own probes and the client session's mid-drag
/// gate all ask "does this net own a pad in that escape zone" of the SAME
/// points, so an approach one of them excuses is excused by all three.
pub fn keepoutPts(arena: std.mem.Allocator, pads: anytype) std.mem.Allocator.Error![]const keepout.PadPt {
    const out = try arena.alloc(keepout.PadPt, pads.len);
    for (pads, out) |p, *o| o.* = .{
        .net = p.net,
        .x = (p.x0 + p.x1) / 2,
        .y = (p.y0 + p.y1) / 2,
        .guard = if (guards(@TypeOf(p), p)) .{
            .bounds = .{ p.x0, p.y0, p.x1, p.y1 },
            .poly = p.poly,
            .layer = p.layer,
            .thru = p.thru,
        } else null,
    };
    return out;
}

/// Project a world pad list into the connectivity oracle's terminals.
///
/// `identity` folds a generated bypass stub onto the net it splits off (see
/// `net_identity`), which the DRC's own topology audit wants and the routing
/// cleanup pass does not — the cleanup reads copper it is about to rewrite, and
/// two nets it may not merge must stay two. `Identity{}` is the exact-identity
/// default, so a caller with nothing to canonicalise passes it and gets the raw
/// net back.
pub fn topologyTerminals(
    arena: std.mem.Allocator,
    pads: anytype,
    identity: net_identity.Identity,
) std.mem.Allocator.Error![]const copper_topology.Terminal {
    const out = try arena.alloc(copper_topology.Terminal, pads.len);
    for (pads, out) |pad, *terminal| terminal.* = .{
        .shape = .{ .x0 = pad.x0, .y0 = pad.y0, .x1 = pad.x1, .y1 = pad.y1, .poly = pad.poly },
        .net = identity.canonical(pad.net),
        .layer = pad.layer,
        .thru = pad.thru,
    };
    return out;
}

// ── Tests ────────────────────────────────────────────────────────────────────

const testing = std.testing;

/// A pad shaped like the router's obstacle entries: no `npth` field at all.
const PlainPad = struct {
    x0: f64,
    y0: f64,
    x1: f64,
    y1: f64,
    poly: []const [2]f64 = &.{},
    net: i32,
    layer: u8 = 0,
    thru: bool = false,
};

/// A pad shaped like the DRC's, which carries the non-plated flag.
const DrilledPad = struct {
    x0: f64,
    y0: f64,
    x1: f64,
    y1: f64,
    poly: []const [2]f64 = &.{},
    net: i32,
    layer: u8 = 0,
    thru: bool = false,
    npth: bool = false,
};

// spec: placement/router - one shared projection turns a world pad list into the keepout escape terminals, guarding only netted plated copper
test "keepout projection guards netted copper and skips a non-plated hole" {
    var arena_inst = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_inst.deinit();
    const arena = arena_inst.allocator();

    const drilled = [_]DrilledPad{
        .{ .x0 = 0, .y0 = 0, .x1 = 1, .y1 = 2, .net = 3, .layer = 1, .thru = true },
        .{ .x0 = 4, .y0 = 0, .x1 = 6, .y1 = 2, .net = 3, .npth = true },
        .{ .x0 = 8, .y0 = 0, .x1 = 9, .y1 = 1, .net = -1 },
    };
    const pts = try keepoutPts(arena, &drilled);
    // Every pad is an escape terminal at its own copper centre …
    try testing.expectEqual(@as(usize, 3), pts.len);
    try testing.expectEqual(@as(f64, 0.5), pts[0].x);
    try testing.expectEqual(@as(f64, 1), pts[0].y);
    // … but only the netted, plated one guards, carrying its face and bounds.
    try testing.expect(pts[0].guard != null);
    try testing.expectEqual(@as(u8, 1), pts[0].guard.?.layer);
    try testing.expect(pts[0].guard.?.thru);
    try testing.expect(pts[1].guard == null); // non-plated: no copper to protect
    try testing.expect(pts[2].guard == null); // no net: no class, so no halo

    // A pad type with no `npth` field at all — the router's obstacle set, where
    // every entry is real copper — still guards on the net test alone.
    const plain = [_]PlainPad{.{ .x0 = 4, .y0 = 0, .x1 = 6, .y1 = 2, .net = 3 }};
    const obs_pts = try keepoutPts(arena, &plain);
    try testing.expect(obs_pts[0].guard != null);
}

// spec: placement/router - the shared topology projection canonicalises pad nets only for the caller that asks for it
test "topology terminals canonicalise a net only under a caller's identity" {
    var arena_inst = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_inst.deinit();
    const arena = arena_inst.allocator();

    const pads = [_]PlainPad{.{ .x0 = 0, .y0 = 0, .x1 = 1, .y1 = 1, .net = 1, .thru = true }};
    // Exact identity (the default) hands the raw net straight back.
    const raw = try topologyTerminals(arena, &pads, .{});
    try testing.expectEqual(@as(i32, 1), raw[0].net);
    try testing.expect(raw[0].shape.x1 == 1 and raw[0].thru);

    // An identity that folds net 1 onto net 0 reaches the terminal.
    const folded = try topologyTerminals(arena, &pads, .{ .owner = &[_]i32{ 0, 0 } });
    try testing.expectEqual(@as(i32, 0), folded[0].net);
}
