//! HTTP page handlers and home-card view models for the design dashboard.
//! Keeps server-side summaries, template rendering, and card tests together.

const std = @import("std");
const httpz = @import("httpz");
const clock = @import("../infra/clock.zig");
const Evaluator = @import("../eval/evaluator.zig").Evaluator;
const env_mod = @import("../eval/env.zig");
const serve_root = @import("../serve.zig");
const Server = serve_root.Server;
const bom_html = @import("bom_html.zig");
const assets_css = @import("assets_css.zig");
const navbar = @import("navbar.zig");
const library = @import("library.zig");
const mcp_tools = @import("mcp_tools.zig");
const modules_page = @import("modules.zig");
const system_review_api = @import("system_review_api.zig");
const home_template = @import("templates/pages.zig");
const layout_status = @import("../layout_status.zig");

/// Error set for HTTP handlers in this module: only writer-side errors
/// propagate back to httpz; everything else is caught internally and
/// translated to a 5xx body.
pub const HandlerError = std.mem.Allocator.Error || std.Io.Writer.Error;

/// GET / — render the home page: a card grid of every `.sexp` design under
/// `src/` (title, instance/net counts, recent mtime, and PCB stage progress)
/// followed by a card grid of every `lib/modules/` module with its
/// parameter list and the designs that instantiate it. The markup itself
/// is generated by the `zt` template at `templates/pages.zt`.
pub fn indexPage(ctx: *Server, _: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const home = gatherHome(ctx.allocator, ctx.project_dir);
    const now_sec: i64 = @intCast(@divTrunc(clock.nanoTimestamp(), clock.ns_per_s));

    var aw: std.Io.Writer.Allocating = .init(ctx.allocator);
    try home_template.Home.render(.{ home.system_cards, home.design_cards, home.module_cards, now_sec }, &aw.writer);
    res.body = aw.written();
    res.content_type = .HTML;
}

/// Everything the home page shows, minus the rendering: the design summaries,
/// the module entries, and each card's search haystack + ★ flag.
pub const HomeData = struct {
    summaries: []const mcp_tools.DesignSummary,
    system_cards: []const home_template.SystemCardVM,
    design_cards: []const home_template.DesignCardVM,
    module_cards: []const home_template.ModuleCardVM,
};

/// Gather the home page's data. Every read here is served from a
/// cross-request cache on a warm process, so this is also exactly what the
/// startup warm-up runs to FILL those caches — see `serve/warmup.zig`. The two
/// callers share this one function so a warm-up can never populate a different
/// set of caches than a render consults.
pub fn gatherHome(allocator: std.mem.Allocator, project_dir: []const u8) HomeData {
    const summaries = mcp_tools.listDesignSummaries(allocator, project_dir) catch &[_]mcp_tools.DesignSummary{};
    const modules = collectHomeModules(allocator, project_dir, summaries) catch &[_]home_template.ModuleHomeEntry{};
    return .{
        .summaries = summaries,
        .system_cards = buildSystemCards(allocator, project_dir) catch &[_]home_template.SystemCardVM{},
        .design_cards = buildDesignCards(allocator, project_dir, summaries) catch &[_]home_template.DesignCardVM{},
        .module_cards = buildModuleCards(allocator, modules) catch &[_]home_template.ModuleCardVM{},
    };
}

/// Pair every design summary with the search haystack the home page's
/// client-side filter AND-matches query terms against, plus its "starred"
/// flag. The starred flag is read fresh from the design's `.layouts.json`
/// sidecar (NOT from the read-set-cached summary) so starring a layout shows
/// up on the next home load.
fn buildDesignCards(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
    summaries: []const mcp_tools.DesignSummary,
) ![]home_template.DesignCardVM {
    const out = try allocator.alloc(home_template.DesignCardVM, summaries.len);
    for (summaries, out) |s, *card| {
        const starred = layout_status.read(allocator, project_dir, s.name).starred;
        card.* = .{
            .s = s,
            .has_starred = starred,
            .search = try designSearchText(allocator, s, starred),
        };
    }
    return out;
}

/// Enumerate the project's system-review workspaces as home cards. Reuses the
/// same enumeration `/api/systems` serves, so the page and the endpoint can
/// never disagree about which systems exist. A project with no `src/systems`
/// yields none and the section simply does not appear.
fn buildSystemCards(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
) ![]home_template.SystemCardVM {
    const summaries = try system_review_api.collectSystemSummaries(allocator, project_dir);
    const out = try allocator.alloc(home_template.SystemCardVM, summaries.len);
    for (summaries, out) |summary, *card| {
        const entry: home_template.SystemHomeEntry = .{
            .name = summary.name,
            .title = summary.title,
            .part_number = summary.part_number,
            .revision = summary.revision,
            .boards = summary.boards,
            .documents = summary.documents,
            .attested = summary.attested,
        };
        card.* = .{ .sys = entry, .search = try systemSearchText(allocator, entry) };
    }
    return out;
}

/// "system <name> <title> <part-number> <revision>" — the searchable text for
/// a system card. The leading tag word mirrors the visible type tag the way
/// the design and module haystacks do, so "system" surfaces exactly these.
fn systemSearchText(
    allocator: std.mem.Allocator,
    entry: home_template.SystemHomeEntry,
) std.mem.Allocator.Error![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    try buf.appendSlice(allocator, "system ");
    try buf.appendSlice(allocator, entry.name);
    for ([_][]const u8{ entry.title, entry.part_number, entry.revision }) |part| {
        if (part.len == 0) continue;
        try buf.append(allocator, ' ');
        try buf.appendSlice(allocator, part);
    }
    if (entry.attested) try buf.appendSlice(allocator, " attested");
    // `toOwnedSlice`, not `buf.items`: the list's capacity can exceed its
    // length, so `items` is not a freeable allocation. The sibling design and
    // module haystacks get away with returning `items` only because the page
    // allocator never frees them — this one is exercised by a test that does.
    return buf.toOwnedSlice(allocator);
}

/// Pair every module entry with its search haystack.
fn buildModuleCards(
    allocator: std.mem.Allocator,
    modules: []const home_template.ModuleHomeEntry,
) ![]home_template.ModuleCardVM {
    const out = try allocator.alloc(home_template.ModuleCardVM, modules.len);
    for (modules, out) |m, *card| {
        card.* = .{ .m = m, .search = try moduleSearchText(allocator, m) };
    }
    return out;
}

/// "<role> <name> <title> <section…>" — the searchable text for a design
/// card. The leading role tag word ("board" or "subcircuit") makes a query of
/// either word surface the matching cards (mirroring the visible type tag);
/// the "grouping"/"starred" tag words mirror the visible status tags so the
/// same words filter them.
fn designSearchText(
    allocator: std.mem.Allocator,
    s: mcp_tools.DesignSummary,
    starred: bool,
) std.mem.Allocator.Error![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    try buf.appendSlice(allocator, if (s.is_board) "board " else "subcircuit ");
    try buf.appendSlice(allocator, s.name);
    if (s.title.len > 0) {
        try buf.append(allocator, ' ');
        try buf.appendSlice(allocator, s.title);
    }
    for (s.sections) |sec| {
        try buf.append(allocator, ' ');
        try buf.appendSlice(allocator, sec);
    }
    try appendTagWords(allocator, &buf, s.has_groups, starred);
    return buf.items;
}

/// Append the " grouping"/" starred" haystack words so a text query of either
/// tag word filters to the cards showing it. Shared by design + module cards.
fn appendTagWords(
    allocator: std.mem.Allocator,
    buf: *std.ArrayList(u8),
    has_groups: bool,
    starred: bool,
) std.mem.Allocator.Error!void {
    if (has_groups) try buf.appendSlice(allocator, " grouping");
    if (starred) try buf.appendSlice(allocator, " starred");
}

/// "subcircuit <name> <params> <doc>" — the searchable text for a module
/// card. Modules are reusable subcircuits, so the leading role tag word is
/// "subcircuit" (matching the visible type tag + the Subcircuits filter).
fn moduleSearchText(
    allocator: std.mem.Allocator,
    m: home_template.ModuleHomeEntry,
) std.mem.Allocator.Error![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    try buf.appendSlice(allocator, "subcircuit ");
    try buf.appendSlice(allocator, m.name);
    if (m.params.len > 0) {
        try buf.append(allocator, ' ');
        try buf.appendSlice(allocator, m.params);
    }
    if (m.doc.len > 0) {
        try buf.append(allocator, ' ');
        try buf.appendSlice(allocator, m.doc);
    }
    try appendTagWords(allocator, &buf, m.has_groups, m.has_starred);
    return buf.items;
}

/// Join the lib/modules inventory with each design's `modules_used` list so
/// every module card can say which designs instantiate it.
fn collectHomeModules(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
    summaries: []const mcp_tools.DesignSummary,
) ![]home_template.ModuleHomeEntry {
    const mods = try modules_page.collectModules(allocator, project_dir);
    var entries: std.ArrayList(home_template.ModuleHomeEntry) = .empty;
    for (mods) |m| {
        var used_by: std.ArrayList([]const u8) = .empty;
        for (summaries) |s| {
            for (s.modules_used) |u| {
                if (std.mem.eql(u8, u, m.name)) {
                    try used_by.append(allocator, s.name);
                    break;
                }
            }
        }
        try entries.append(allocator, .{
            .name = m.name,
            .params = m.params,
            .doc = m.doc,
            .used_by = try used_by.toOwnedSlice(allocator),
            .has_groups = m.has_groups,
            // Read fresh each load so starring a module's layout shows up here.
            .has_starred = layout_status.read(allocator, project_dir, m.name).starred,
        });
    }
    return entries.toOwnedSlice(allocator);
}

/// GET /style.css — serve the static stylesheet shared by the index page
/// and other plain-HTML pages so they pick up the dark theme without
/// inlining the CSS into every response.
pub fn cssPage(_: *Server, _: *httpz.Request, res: *httpz.Response) HandlerError!void {
    res.content_type = .CSS;
    res.body = assets_css.index_css;
}

// spec: Web Server - The navigation bar routes home through the Netlisp brand and carries no separate Designs tab
test "navbar keeps the user-facing destinations" {
    var aw: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer aw.deinit();
    try home_template.Navbar.render(.{"designs"}, &aw.writer);
    const html = aw.written();

    var shared: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer shared.deinit();
    try navbar.write(&shared.writer, .home);
    try std.testing.expectEqualStrings(shared.written(), html);

    // The brand IS the route home — it must be an anchor to `/`, not a label.
    try std.testing.expect(std.mem.indexOf(u8, html, "<a href=\"/\" class=\"brand active\" aria-current=\"page\">Netlisp</a>") != null);
    // …and it is the ONLY link to `/`: the separate Designs tab is gone.
    try std.testing.expect(std.mem.indexOf(u8, html, ">Designs<") == null);
    // Library remains, while internal tool surfaces do not appear as tabs.
    try std.testing.expect(std.mem.indexOf(u8, html, "href=\"/library\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "href=\"/route-review\"") == null);
    try std.testing.expect(std.mem.indexOf(u8, html, ">MCP</a>") == null);

    // The brand must still read as a link once the generic `.navbar a` colour
    // rule applies to it.
    const navbar_css = @embedFile("assets/navbar.css");
    try std.testing.expect(std.mem.indexOf(u8, navbar_css, ".navbar a.brand:hover") != null);
}

// spec: Web Server - home design cards lazily show the same six-stage PCB completion tracker as the layout editor
test "home design cards wire the compact layout-progress endpoint" {
    const template = @embedFile("templates/pages.zt");
    const routes = @embedFile("../serve.zig");
    try std.testing.expect(std.mem.indexOf(u8, template, "data-layout-progress") != null);
    try std.testing.expect(std.mem.indexOf(u8, template, "fetch('/api/layout-progress/'") != null);
    try std.testing.expect(std.mem.indexOf(u8, routes, "router.get(\"/api/layout-progress/:name\"") != null);
}

// spec: Web Server - home design cards put issue counts only in stage one and omit legacy issue/section chips
test "home design cards keep issue counts inside schematic progress" {
    const summary: mcp_tools.DesignSummary = .{
        .name = "power_board",
        .title = "Power board",
        .sections = &.{ "Input", "Regulation" },
        .instance_count = 4,
        .net_count = 3,
        .mtime_sec = 0,
        .build_ok = true,
        .erc_errors = 2,
        .erc_warnings = 1,
        .assert_fails = 3,
        .open_notes = 4,
        .is_board = true,
    };
    var aw: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer aw.deinit();
    try home_template.DesignCard.render(.{ summary, "board power input regulation", false, 0 }, &aw.writer);
    const html = aw.written();

    try std.testing.expect(std.mem.indexOf(u8, html, "data-progress-name=\"power_board\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "data-erc-errors=\"2\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "data-erc-warnings=\"1\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "data-assert-fails=\"3\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "data-open-notes=\"4\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "status-chips") == null);
    try std.testing.expect(std.mem.indexOf(u8, html, "design-card-sections") == null);
}

// spec: Web Server - The home page lists every `src/systems/` review workspace as its own card kind, from the same enumeration `/api/systems` serves, so a system is reachable without knowing its URL
test "home system cards carry the workspace link, identity and filter kind" {
    const entry: home_template.SystemHomeEntry = .{
        .name = "barracuda",
        .title = "Barracuda OC-303-1-01",
        .part_number = "OC-303-1-01",
        .revision = "B3",
        .boards = 2,
        .documents = 19,
        .attested = true,
    };
    var aw: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer aw.deinit();
    try home_template.SystemCard.render(.{ entry, "system barracuda" }, &aw.writer);
    const html = aw.written();

    // The whole point of the card: a route into the workspace. Before this,
    // /systems/:name was reachable only by typing the URL — nothing in the UI
    // linked it and /systems itself 404s.
    try std.testing.expect(std.mem.indexOf(u8, html, "href=\"/systems/barracuda\"") != null);
    // Its own kind, so the Systems filter button selects exactly these.
    try std.testing.expect(std.mem.indexOf(u8, html, "data-kind=\"system\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "Barracuda OC-303-1-01") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "OC-303-1-01 rev B3") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "2 boards") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "19 documents") != null);
    try std.testing.expect(std.mem.indexOf(u8, html, "attested") != null);
    // It rides the shared card class, so the existing search/filter script
    // (which selects `#home-grid .design-card`) picks it up with no JS change.
    try std.testing.expect(std.mem.indexOf(u8, html, "class=\"design-card\"") != null);
}

// spec: Web Server - A system card's search text leads with its kind word and carries its identity, so the home page's existing search box and its Systems filter both surface it with no extra client script
test "home system search text and filter tab make a system findable by name and kind" {
    const entry: home_template.SystemHomeEntry = .{
        .name = "barracuda",
        .title = "Barracuda OC-303-1-01",
        .part_number = "OC-303-1-01",
        .revision = "B3",
        .boards = 2,
        .documents = 19,
        .attested = true,
    };
    const search = try systemSearchText(std.testing.allocator, entry);
    defer std.testing.allocator.free(search);
    // The leading tag word mirrors the visible tag the way design/module
    // haystacks do, so a query of "system" surfaces exactly these cards.
    try std.testing.expect(std.mem.startsWith(u8, search, "system barracuda"));
    try std.testing.expect(std.mem.indexOf(u8, search, "OC-303-1-01") != null);
    try std.testing.expect(std.mem.indexOf(u8, search, "B3") != null);
    try std.testing.expect(std.mem.indexOf(u8, search, "attested") != null);

    // An empty identity field must not leave a double space that a two-term
    // query would then fail to match across.
    const bare = try systemSearchText(std.testing.allocator, .{
        .name = "spare",
        .title = "",
        .part_number = "",
        .revision = "",
        .boards = 0,
        .documents = 0,
    });
    defer std.testing.allocator.free(bare);
    try std.testing.expectEqualStrings("system spare", bare);

    // The card kind is worthless without the tab that selects it.
    const template = @embedFile("templates/pages.zt");
    try std.testing.expect(std.mem.indexOf(u8, template, ".{ .id = \"system\", .label = \"Systems\" }") != null);
}

// spec: Web Server - Phone-width Design, Library, Schematic, and Assembly pages use touch-sized navigation, single-column content, and board-first inspection without horizontal page overflow
test "primary web pages expose a consistent phone layout" {
    const navbar_css = @embedFile("assets/navbar.css");
    try std.testing.expect(std.mem.indexOf(u8, navbar_css, "min-height:44px") != null);
    try std.testing.expect(std.mem.indexOf(u8, navbar_css, "overflow-x:auto") != null);

    const home = @embedFile("templates/pages.zt");
    try std.testing.expect(std.mem.indexOf(u8, home, "viewport-fit=cover") != null);
    try std.testing.expect(std.mem.indexOf(u8, home, ".home-newrow{flex-direction:column") != null);
    try std.testing.expect(std.mem.indexOf(u8, home, "grid-template-columns:minmax(0,1fr)") != null);

    const library_template_source = @embedFile("templates/library.zt");
    const library_css = @embedFile("assets/library.css");
    try std.testing.expect(std.mem.indexOf(u8, library_template_source, "viewport-fit=cover") != null);
    try std.testing.expect(std.mem.indexOf(u8, library_css, ".upload-file-grid { flex-direction:column") != null);
    try std.testing.expect(std.mem.indexOf(u8, library_css, ".card-grid { grid-template-columns:minmax(0,1fr)") != null);

    const schematic_css = @embedFile("../assets/schematic_inline.css");
    try std.testing.expect(std.mem.indexOf(u8, schematic_css, ".sch-sidebar{order:-1") != null);
    try std.testing.expect(std.mem.indexOf(u8, schematic_css, ".head-links .viewtoggle{display:flex") != null);
    try std.testing.expect(std.mem.indexOf(u8, schematic_css, ".schematic-mode-slider{position:relative") != null);
    try std.testing.expect(std.mem.indexOf(u8, schematic_css, ".schematic-mode-switch{flex:1 0 100%") != null);

    const assembly_css = @embedFile("assets/assembly_debug.css");
    try std.testing.expect(std.mem.indexOf(u8, assembly_css, ".board-pane { order:-1") != null);
    try std.testing.expect(std.mem.indexOf(u8, assembly_css, "bottom:6px;left:6px") != null);
}

// spec: Web Server - The home page's data gather runs without a request, so the startup warm-up fills exactly the caches a render reads
test "gatherHome runs off-request and reports each design's starred flag" {
    const testing = std.testing;
    var tmp = testing.tmpDir(.{});
    defer tmp.cleanup();
    try tmp.dir.createDir(std.testing.io, "src", .default_dir);
    try tmp.dir.createDir(std.testing.io, "src/boards", .default_dir);
    try tmp.dir.writeFile(std.testing.io, .{ .sub_path = "src/boards/alpha.sexp", .data = "(design-block \"Alpha\")" });
    try tmp.dir.writeFile(std.testing.io, .{
        .sub_path = "src/boards/alpha.layouts.json",
        .data = "{\"default\":\"hand\",\"layouts\":[{\"name\":\"hand\",\"kind\":\"manual\",\"ts\":2,\"parts\":[]}]}",
    });
    const root = try tmp.dir.realPathFileAlloc(std.testing.io, ".", testing.allocator);
    defer testing.allocator.free(root);

    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();

    // No httpz request, no Server — this is exactly how `serve/warmup.zig`
    // calls it on its background thread. It must produce the same cards the
    // page renders, star included (read through the nested sidecar, which
    // only resolves if the src index found it).
    const home = gatherHome(arena_state.allocator(), root);
    try testing.expectEqual(@as(usize, 1), home.design_cards.len);
    try testing.expectEqualStrings("alpha", home.design_cards[0].s.name);
    try testing.expect(home.design_cards[0].has_starred);
}
